apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  startingDeadlineSeconds: 200
  concurrencyPolicy: Forbid
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      name: my-simple-job
    spec:
      activeDeadlineSeconds: 200
      ttlSencondsAfterFinisheb: 10
      parallelism: 3
      completions: 3
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: my-job-container
              image: busybox
              command: ["sh","-c","sleep 10"]