apiVersion: batch/v1
kind: Job
metadata:
  name: my-simple-job
spec:
  activeDeadlineSeconds: 200
  ttlSencondsAfterFinisheb: 10
  parallelism: 1
  completions: 3
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: my-job-container
          image: busybox
          command: ["sh","-c","sleep 5"]