apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-set
spec:
  replicas: 2
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
